#############################################################################
# Makefile for building: final
# Generated by qmake (2.01a) (Qt 4.7.0) on: Sun Dec 16 18:25:10 2012
# Project:  final.pro
# Template: app
# Command: /course/cs123/bin/cs123_qmake -o Makefile final.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DTIXML_USE_STL -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O3 -W -Waddress -Warray-bounds -Wc++0x-compat -Wchar-subscripts -Wformat -Wmain -Wmissing-braces -Wparentheses -Wreorder -Wreturn-type -Wsequence-point -Wsign-compare -Wstrict-aliasing -Wstrict-overflow=1 -Wswitch -Wtrigraphs -Wuninitialized -Wunused-label -Wunused-variable -Wvolatile-register-var -Wno-extra -D_REENTRANT $(DEFINES)
INCPATH       = -I/course/cs123/lib/qt/qt-4.7.0/mkspecs/default -I. -I/course/cs123/lib/qt/qt-4.7.0/include/QtCore -I/course/cs123/lib/qt/qt-4.7.0/include/QtGui -I/course/cs123/lib/qt/qt-4.7.0/include/QtOpenGL -I/course/cs123/lib/qt/qt-4.7.0/include/QtXml -I/course/cs123/lib/qt/qt-4.7.0/include -Ibrush -Icamera -Ilib -Imath -Iscenegraph -Iui -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/course/cs123/lib/qt/qt-4.7.0/lib
LIBS          = $(SUBLIBS)  -L/course/cs123/lib/qt/qt-4.7.0//lib -L/usr/X11R6/lib -lQtXml -L/course/cs123/lib/qt/qt-4.7.0//lib -lQtOpenGL -L/usr/X11R6/lib -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /course/cs123/bin/cs123_qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		scenegraph/Point.cpp \
		scenegraph/Scene.cpp \
		math/CS123Matrix.cpp \
		lib/CS123XmlSceneParser.cpp \
		ui/mainwindow.cpp \
		ui/view.cpp \
		ui/Canvas2D.cpp \
		ui/SupportCanvas2D.cpp \
		camera/CamtransCamera.cpp moc_mainwindow.cpp \
		moc_view.cpp \
		moc_Canvas2D.cpp \
		moc_SupportCanvas2D.cpp
OBJECTS       = main.o \
		Point.o \
		Scene.o \
		CS123Matrix.o \
		CS123XmlSceneParser.o \
		mainwindow.o \
		view.o \
		Canvas2D.o \
		SupportCanvas2D.o \
		CamtransCamera.o \
		moc_mainwindow.o \
		moc_view.o \
		moc_Canvas2D.o \
		moc_SupportCanvas2D.o
DIST          = ../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/g++.conf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/unix.conf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/linux.conf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/qconfig.pri \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_functions.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_config.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_pre.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/release.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_post.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/warn_on.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/opengl.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/thread.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/moc.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/resources.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/uic.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/yacc.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/lex.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/include_source_dir.prf \
		final.pro
QMAKE_TARGET  = final
DESTDIR       = 
TARGET        = final

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: final.pro  /course/cs123/lib/qt/qt-4.7.0/mkspecs/default/qmake.conf ../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/g++.conf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/unix.conf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/linux.conf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/qconfig.pri \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_functions.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_config.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/exclusive_builds.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_pre.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/release.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_post.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/warn_on.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/opengl.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/thread.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/moc.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/resources.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/uic.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/yacc.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/lex.prf \
		../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/include_source_dir.prf \
		/course/cs123/lib/qt/qt-4.7.0/lib/libQtXml.prl \
		/course/cs123/lib/qt/qt-4.7.0/lib/libQtCore.prl \
		/course/cs123/lib/qt/qt-4.7.0/lib/libQtOpenGL.prl \
		/course/cs123/lib/qt/qt-4.7.0/lib/libQtGui.prl
	$(QMAKE) -o Makefile final.pro
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/g++.conf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/unix.conf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/common/linux.conf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/qconfig.pri:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_functions.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt_config.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/exclusive_builds.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_pre.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/release.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/default_post.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/warn_on.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/qt.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/opengl.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/unix/thread.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/moc.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/resources.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/uic.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/yacc.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/lex.prf:
../../../../sys/shared/psfu/contrib/projects/qt/qt-4.7.0/mkspecs/features/include_source_dir.prf:
/course/cs123/lib/qt/qt-4.7.0/lib/libQtXml.prl:
/course/cs123/lib/qt/qt-4.7.0/lib/libQtCore.prl:
/course/cs123/lib/qt/qt-4.7.0/lib/libQtOpenGL.prl:
/course/cs123/lib/qt/qt-4.7.0/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile final.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/final1.0.0 || $(MKDIR) .tmp/final1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/final1.0.0/ && $(COPY_FILE) --parents scenegraph/Point.h scenegraph/Scene.h math/CS123Algebra.h math/TA_Tester.h lib/CS123Common.h lib/CS123ISceneParser.h lib/CS123SceneData.h lib/CS123XmlSceneParser.h ui/mainwindow.h ui/view.h ui/Canvas2D.h ui/SupportCanvas2D.h camera/CamtransCamera.h camera/Camera.h .tmp/final1.0.0/ && $(COPY_FILE) --parents main.cpp scenegraph/Point.cpp scenegraph/Scene.cpp math/CS123Matrix.cpp lib/CS123XmlSceneParser.cpp ui/mainwindow.cpp ui/view.cpp ui/Canvas2D.cpp ui/SupportCanvas2D.cpp camera/CamtransCamera.cpp .tmp/final1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/final1.0.0/ && (cd `dirname .tmp/final1.0.0` && $(TAR) final1.0.0.tar final1.0.0 && $(COMPRESS) final1.0.0.tar) && $(MOVE) `dirname .tmp/final1.0.0`/final1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/final1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check:

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp moc_Canvas2D.cpp moc_SupportCanvas2D.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp moc_Canvas2D.cpp moc_SupportCanvas2D.cpp
moc_mainwindow.cpp: ui/mainwindow.h
	/course/cs123/lib/qt/qt-4.7.0//bin/moc $(DEFINES) $(INCPATH) ui/mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: ui/view.h
	/course/cs123/lib/qt/qt-4.7.0//bin/moc $(DEFINES) $(INCPATH) ui/view.h -o moc_view.cpp

moc_Canvas2D.cpp: ui/SupportCanvas2D.h \
		lib/CS123Common.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123SceneData.h \
		ui/Canvas2D.h
	/course/cs123/lib/qt/qt-4.7.0//bin/moc $(DEFINES) $(INCPATH) ui/Canvas2D.h -o moc_Canvas2D.cpp

moc_SupportCanvas2D.cpp: lib/CS123Common.h \
		ui/SupportCanvas2D.h
	/course/cs123/lib/qt/qt-4.7.0//bin/moc $(DEFINES) $(INCPATH) ui/SupportCanvas2D.h -o moc_SupportCanvas2D.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		ui/Canvas2D.h \
		ui/SupportCanvas2D.h \
		lib/CS123Common.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123SceneData.h
	/course/cs123/lib/qt/qt-4.7.0/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ui/mainwindow.h \
		lib/CS123XmlSceneParser.h \
		lib/CS123ISceneParser.h \
		lib/CS123SceneData.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123Common.h \
		scenegraph/Scene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Point.o: scenegraph/Point.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o scenegraph/Point.cpp

Scene.o: scenegraph/Scene.cpp scenegraph/Scene.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123Common.h \
		lib/CS123SceneData.h \
		lib/CS123ISceneParser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o scenegraph/Scene.cpp

CS123Matrix.o: math/CS123Matrix.cpp math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CS123Matrix.o math/CS123Matrix.cpp

CS123XmlSceneParser.o: lib/CS123XmlSceneParser.cpp lib/CS123XmlSceneParser.h \
		lib/CS123ISceneParser.h \
		lib/CS123SceneData.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CS123XmlSceneParser.o lib/CS123XmlSceneParser.cpp

mainwindow.o: ui/mainwindow.cpp ui/mainwindow.h \
		ui_mainwindow.h \
		camera/CamtransCamera.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123Common.h \
		camera/Camera.h \
		lib/CS123XmlSceneParser.h \
		lib/CS123ISceneParser.h \
		lib/CS123SceneData.h \
		scenegraph/Scene.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ui/mainwindow.cpp

view.o: ui/view.cpp ui/view.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o ui/view.cpp

Canvas2D.o: ui/Canvas2D.cpp ui/Canvas2D.h \
		ui/SupportCanvas2D.h \
		lib/CS123Common.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123SceneData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Canvas2D.o ui/Canvas2D.cpp

SupportCanvas2D.o: ui/SupportCanvas2D.cpp ui/SupportCanvas2D.h \
		lib/CS123Common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SupportCanvas2D.o ui/SupportCanvas2D.cpp

CamtransCamera.o: camera/CamtransCamera.cpp camera/CamtransCamera.h \
		math/CS123Algebra.h \
		math/CS123Vector.inl \
		math/CS123Matrix.inl \
		lib/CS123Common.h \
		camera/Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CamtransCamera.o camera/CamtransCamera.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

moc_Canvas2D.o: moc_Canvas2D.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Canvas2D.o moc_Canvas2D.cpp

moc_SupportCanvas2D.o: moc_SupportCanvas2D.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SupportCanvas2D.o moc_SupportCanvas2D.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

