/*!
   @file   mainwindow.h
   @author Ben Herila (ben@herila.net)
   @author Evan Wallace (evan.exe@gmail.com)
   @date   Fall 2010

   @brief  Main window (GUI) class for CS123 projects.
**/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QVariant>
#include <QMainWindow>

namespace Ui {
    class MainWindow;
}

class DataBinding;

/*! @brief The main graphical user interface class (GUI class) for our application.  */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

protected:

    //! Overridden from QWidget. Handles the window resize event.
    virtual void changeEvent(QEvent *e);

    //! Overridden from QWidget. Handles the window close event.
    virtual void closeEvent(QCloseEvent *e);

private:
    // EXCEPTION: 'ui' member which is auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow  *ui;

public slots:

    //! Displays a dialog box to open a 2D image or 3D scene file.
    void fileOpen();

};

#endif // MAINWINDOW_H
